local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>pg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>pk", builtin.keymaps, { desc = "Telescope keymaps" })
vim.keymap.set("n", "<leader>pc", builtin.current_buffer_fuzzy_find, { desc = "Fuzzy inside buffer" })
